version: "3"

services:
  mysql-db:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: password1234
    ports:
      - "3306:3306"
    volumes:
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf"